version: '3'
services:
  api_ml:
    build:
      context: .
      dockerfile: api.Dockerfile
    image: api_image_captioning
    container_name: api_image_captioning
    deploy:
      resources:
        reservations:
          devices:
          - driver: "nvidia"
            device_ids: ["0"]
            capabilities: [gpu]
    ports:
      - 8000:8000
    networks:
      - api_image_captioning
  
  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: start --all --config=ngrok/ngrok.yml 
    ports:
      - 4040:4040
    volumes:
      - ./ngrok/ngrok.yml:/ngrok/ngrok.yml
    networks:
      - api_image_captioning

networks:
  api_image_captioning:
    driver: bridge
